//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class biodataDbEntities : DbContext
    {
        public biodataDbEntities()
            : base("name=biodataDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contactinfo> contactinfoes { get; set; }
        public virtual DbSet<culturalinfo> culturalinfoes { get; set; }
        public virtual DbSet<educationinfo> educationinfoes { get; set; }
        public virtual DbSet<familyinfo> familyinfoes { get; set; }
        public virtual DbSet<personalinfo> personalinfoes { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<socialmedia> socialmedias { get; set; }
        public virtual DbSet<userprofile> userprofiles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<workexperienceinfo> workexperienceinfoes { get; set; }
    }
}
