//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class contactinfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameRelation { get; set; }
        public string ContactNumber { get; set; }
        public string ContactNumberRelation { get; set; }
        public string Email { get; set; }
        public string EmailRelation { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
