//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class familyinfo
    {
        public int Id { get; set; }
        public string FatherName { get; set; }
        public string FatherCity { get; set; }
        public string FatherState { get; set; }
        public string FatherDesignation { get; set; }
        public string FatherCompany { get; set; }
        public string MotherName { get; set; }
        public string MotherCity { get; set; }
        public string MotherState { get; set; }
        public string MotherDesignation { get; set; }
        public string MotherCompany { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
