//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personalinfo
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOBTime { get; set; }
        public string CurrentCity { get; set; }
        public string Height { get; set; }
        public string Complexion { get; set; }
        public string MaritalStatus { get; set; }
        public string Diet { get; set; }
        public string Drink { get; set; }
        public string Smoke { get; set; }
        public string Hobbies { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
