//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int Id { get; set; }
        public byte[] Picture1 { get; set; }
        public byte[] Picture2 { get; set; }
        public byte[] Picture3 { get; set; }
        public byte[] Picture4 { get; set; }
        public byte[] Picture5 { get; set; }
        public byte[] Picture6 { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
