//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class socialmedia
    {
        public int Id { get; set; }
        public string Facebook { get; set; }
        public string Linkedin { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string Quora { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual user user { get; set; }
    }
}
