//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biodata.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.contactinfoes = new HashSet<contactinfo>();
            this.culturalinfoes = new HashSet<culturalinfo>();
            this.educationinfoes = new HashSet<educationinfo>();
            this.familyinfoes = new HashSet<familyinfo>();
            this.personalinfoes = new HashSet<personalinfo>();
            this.pictures = new HashSet<picture>();
            this.socialmedias = new HashSet<socialmedia>();
            this.userprofiles = new HashSet<userprofile>();
            this.workexperienceinfoes = new HashSet<workexperienceinfo>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<contactinfo> contactinfoes { get; set; }
        public virtual ICollection<culturalinfo> culturalinfoes { get; set; }
        public virtual ICollection<educationinfo> educationinfoes { get; set; }
        public virtual ICollection<familyinfo> familyinfoes { get; set; }
        public virtual ICollection<personalinfo> personalinfoes { get; set; }
        public virtual ICollection<picture> pictures { get; set; }
        public virtual ICollection<socialmedia> socialmedias { get; set; }
        public virtual ICollection<userprofile> userprofiles { get; set; }
        public virtual ICollection<workexperienceinfo> workexperienceinfoes { get; set; }
    }
}
